fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: MainBundle\Entity\User
    from_email:
        address: "matthijs0703@hotmail.com"
        sender_name: "matthijs"

twig:
    form_themes: ['bootstrap_3_layout.html.twig']

parameters:
    image_directory: '%kernel.project_dir%/web/uploads/image'