<?php

namespace MainBundle\Repository;

/**
 * ActiviteitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteitRepository extends \Doctrine\ORM\EntityRepository
{
}
