<?php

namespace MainBundle\Repository;

/**
 * HoogseizoenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoogseizoenRepository extends \Doctrine\ORM\EntityRepository
{
}
