<?php

namespace MainBundle\Repository;

/**
 * KamerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamerRepository extends \Doctrine\ORM\EntityRepository
{
}
